[database]

connection_string = "host=localhost port=5435 user=uroot password=qwertyui dbname=db_revamp_1 sslmode=disable"
max_idle_connections = 5
max_open_connections = 20
connection_max_lifetime = "60s"
driver_name = "postgres"
###############################################################################
# HTTP server configuration

[http]

server_address = ":8888"
###############################################################################
